version: '3.8'

services:
    db:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=postgres
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - app-network
    backend:
        image: auth-backend
        ports:
            - '5000:5000'
        environment:
            - NODE_ENV=development
            - PORT=5000
            - JWT_SECRET=supersecretkey
            - DB_HOST=db
            - DB_PORT=5432
            - DB_SCHEMA=public
            - DB_NAME=postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=admin
        depends_on:
            - db
        networks:
            - app-network
networks:
    app-network:
volumes:
    db_data:
